### ISSUE TITLE
Movement keys are bound to super

### ISSUE THREAD

**Issue by nanomonkey** [zkry/asm-blox#20]
There are some block movement keys that are bound to super and then an arrow key.  My window managers (i3 and sway on Linux) are currently set to use the Windows key as super.  I know I'm not the only one that does this, so I was wondering if these could be switched to meta or shift (ie "<M-right>" or "<S-right>").  Or perhaps make it a customizable option.

Note, I've already made the change locally, so it's not a big problem if you want to keep it as it is.

**Comment by nanomonkey** [comment]
Oh, and thanks.  I'm enjoying the game.

**Comment by zkry** [comment]
I'm glad you're enjoying it! Now that you mention it, I guess binding things to super isn't really that good for a package to do. I'll also bind these commands to the meta-arrow keys.
