### ISSUE TITLE
Instructions about input-ports on modules are a bit too minimal.

### ISSUE THREAD

**Issue by nanomonkey** [zkry/asm-blox#21]
The tutorial game "Editor Basics" was a bit of a jump in complexity.  It may need to be pushed further down in the series, or some more information should be given in the instructions.

For my solution I needed to send the characters for "Hello World" from two blocks, as one block couldn't hold enough commands.  I used a stack with the "input-ports" option.  The instructions don't explain that the ports need to be in an s-expression (in parenthesis):  
`:input-ports (up down left)`

This left me wondering where else a list was an option...although I assume there aren't any.

`block`, `loop`, `br` and `br_if` are also a little sparse in examples or usage.  A few more choice hints may be useful, specially since `br_if` acts almost opposite between the two.  Maybe a reference to folding, or another example. 

I may just be slow... :)

**Comment by zkry** [comment]
Thanks for sharing your experience! Yeah, this game definitely lacks pacing and production quality so it's really helpful to know where these rough edges lie.

I'll document that the input-ports needs to be an s-expression. I'll also add more examples about the loop constructs. Also if you feel like any other component being able to take lists of ports would be helpful I can definitely add that too.
