### ISSUE TITLE
completion-at-point integration

### ISSUE THREAD

**Issue by zkry** [zkry/asm-blox#5]
In order to assist in writing code, it may be helpful to write a company-mode integration that completes the various commands.

**Comment by danilevy1212** [comment]
Better use a `completion-at-point-function` which users can interact with the the `company-completion-at-point` backend. A lot of users are using `corfu` these days too, and it works with `completion-at-point-functions` as well.

**Comment by zkry** [comment]
Great point! I'll update this ticket.
