### ISSUE TITLE
Design: Reconsider YAML

### ISSUE THREAD

**Issue by progfolio** [zkry/asm-blox#8]
Not that there's anything particularly wrong with YAML, but s-expressions are just as well suited for expressing the data for constructing components. I can imagine something of the form `(TYPE PROPERTIES...)`. e.g.

```
(heap
 :API    1
 :size   100
 :ports ( :up   (set peek)
          :left (seek offset)))
```

**Comment by zkry** [comment]
I like this idea. I chose YAML pretty much on a whim (perhaps to give the game a grungy Kubernetes vibe).  It seems a YAML-based game is sort of an oxymoron 😄 . Plus it wouldn't be hard adding this in a non-breaking way.

**Comment by progfolio** [comment]
You'd be able to ditch the dependency on the yaml package, too.

**Comment by zkry** [comment]
That's true. Not relying on any external dependencies is a huge plus.
